### ISSUE TITLE
商品ページをホームページに設定すると商品一覧等が表示されない

### ISSUE THREAD

**Issue by artovenry** [pepabo/colormeshop-wp-plugin#124]
$page_idがクエリーされないのが原因、、、？

**Comment by ackintosh** [comment]
私の方でも、今ローカルで試した感じですと、商品ページをホームページに設定するとNot Foundになってしまいました 🤔 

![image](https://user-images.githubusercontent.com/1885716/84749152-8ff06980-aff4-11ea-9772-27f2346aa43d.png)

デバッグしてみた限り ↓ で404を表示する条件分岐に入っているようです 💡 

https://github.com/pepabo/colormeshop-wp-plugin/blob/5d08f9bb508248c45fa960a9e0f1804ddc2837ff/src/class-plugin.php#L181-L183

**Comment by ackintosh** [comment]
もしかしたら、そもそもこの条件分岐は必要ないかもしれませんね 🤔 

この条件分岐の意図は、「商品ページへのアクセスだけど、`colorme_item` (商品ID)がクエリパラメータに無ければ、表示すべき商品がわからない」からエラーを表示していると理解しているのですが、

例えば、ショートコード `[colormeshop_page]` の仕様として
商品IDの指定の仕方は2つあって、ショートコードの中で指定することもできます（下記の2つめ）。

```
# クエリパラメータの `colorme_item` の商品IDが使われる
[colormeshop_page]
```

```
# ショートコードで商品IDを指定する
[colormeshop_page product_id="123"]
```

なので、
「ショートコードで商品IDを指定することもできる」ので、 https://github.com/pepabo/colormeshop-wp-plugin/issues/124#issuecomment-644609170 で抜粋した条件分岐は 不要なのではないかと思いました 🤔

**Comment by kenchan** [comment]
@artovenry @ackintosh お返事が遅れて申し訳ありません。

@artovenry が利用されている環境はPHP 7以降でしょうか？もし7以降であれば、近々リリース予定のv2系で対応しようと思います。もし5系でも利用できるv1系にも対応したほうがよければお返事ください。
